package doc

var english = []string{
	"1.0",
	BaseDelimiter,
	Use,
	"",
	Short,
	"",
	Long,
	"",
	Example,
	"",
	HelpFlag,
	"help information for the application.",
	CmdFlags,
	"[flags]",
	ConfigEnvMsg1,
	`The following environment variables are active and could affect the execution
of the program depending on command line arguments:`,
	ConfigEnvMsg2,
	"No variables",
	ConfigEnvMsg3,
	"The following environment variables are available for this program:",
	BaseDelimiter,
	HelpDelimiter,
	Usage,
	"Usage:",
	Aliases,
	"Aliases:",
	Examples,
	"Examples:",
	AvailableCommands,
	"Available Commands:",
	Flags,
	"Flags:",
	GlobalFlags,
	"Global Flags:",
	AdditionalHelpTopics,
	"Additional help topics:",
	ProvidesMoreInformationAboutACommand,
	"provides more information about a command.",
	HelpDelimiter,
	UsageDelimiter,
	HelpCmd,
	"[command]",
	"Help about any command",
	`Help provides help for any command in the application.
Simply type appname help [path to command] for full details.`,
	"",
	ConfigCmd,
	"",
	"Configuration file related commands",
	"",
	"",
	ConfigInitCmd,
	"",
	"Creates a default config file in cwd or where --location is set",
	`When this command is executed a configuration file will be created
in the specified location (in the current directory by default, or governed 
by the value passed to the location flag). This configuration file will contain
all the supported variables with their default values`,
	"",
	ConfigEnvCmd,
	"",
	"Shows the active environment variables that would impact the program",
	"",
	"",
	ConfigDisplayCmd,
	"",
	"Shows the current configuration values",
	`Shows the current configuration values taking into account all environment
and configuration file values. Command-line flags invalid for the config display
command would not be displayed`,
	"",
	VersionCmd,
	"",
	"Prints out the version number of the program",
	"",
	"",
	UsageDelimiter,
	CmdlineDelimiter,
	LogLevel,
	"The log level of the program. Valid values are \"error\", \"warn\", \"info\" and \"debug\"",
	ConfFile,
	"The configuration file location",
	LogFile,
	"The log file location",
	Pretty,
	"If set the console output of the logging calls will be prettified",
	NoEnv,
	"If set the environment variables will not be considered",
	NoCfg,
	"If set no configuration file will be loaded",
	Verbosity,
	"The verbosity of the program, an integer between 0 and 3 inclusive.",
	DoTrace,
	"Enables tracing",
	CfgLocation,
	"Where to write the configuration file, one of \"cwd\", \"user\" or \"system\"",
	CfgForce,
	"If specified, any existing configuration files will be overwritten",
	CmdlineDelimiter,
	ConfigDelimiter,
	ConfigHeader,
	"Configuration generated on {{ date }}",
	ConfigDelimiter,
}
