package doc

var italian = []string{
	"1.0",
	BaseDelimiter,
	Use,
	"",
	Short,
	"",
	Long,
	"",
	Example,
	"",
	HelpFlag,
	"informazioni dell'uso per l'applicazione",
	CmdFlags,
	"[opzioni]",
	ConfigEnvMsg1,
	`Le variabili di sistema seguenti sono attive e potrebbero influenzare
l'esecuzione del programma a seconda dei parametri passati al comando:`,
	ConfigEnvMsg2,
	"Nessuna variabile",
	ConfigEnvMsg3,
	"Le variabili di sistema seguenti sono disponibili per questo programma:",
	BaseDelimiter,
	HelpDelimiter,
	Usage,
	"Uso:",
	Aliases,
	"Alias:",
	Examples,
	"Esempi:",
	AvailableCommands,
	"Comandi disponibili:",
	Flags,
	"Opzioni:",
	GlobalFlags,
	"Opzioni globali:",
	AdditionalHelpTopics,
	"Informazioni addizionali:",
	ProvidesMoreInformationAboutACommand,
	"dá più informazioni su un comando.",
	HelpDelimiter,
	UsageDelimiter,
	"help",
	"[comando]",
	"Informazioni dell'uso per un qualsiasi comando",
	`Help provvede le informazioni dell'uso per un qualsiasi comando dell'applicazione.
Digitate semplicemente nomedellapplicazione help [nome del comando] per i dettagli.`,
	"",
	ConfigCmd,
	"",
	"Comandi relativi alla configurazione",
	"",
	"",
	ConfigInitCmd,
	"",
	"Crea un file di configurazione nella directory corrente o dove é deciso da --location",
	`Quando questo comando é eseguito, un file di configurazione viene creato dove
specificato (nella directory corrente di default, o a seconda del valore della opzione 
location). Questo file di configurazione conterrá tutte le variabili disponibili
inizializzate al loro valore di default.`,
	"",
	ConfigEnvCmd,
	"",
	"Mostra le variabili di sistema relative al programma",
	"",
	"",
	ConfigDisplayCmd,
	"",
	"Mostra la configurazione corrente",
	`Mostra la configurazione corrente tenendo in conto le variabili di sistema e
il file di configurazione. Opzioni passate sulla linea di comando che non sono
validi per il comando config display non saranno disponibili`,
	"",
	VersionCmd,
	"",
	"Mostra la versione del programma",
	"",
	"",
	UsageDelimiter,
	CmdlineDelimiter,
	LogLevel,
	"Il livello di logging del programma. Valori validi sono \"error\", \"warn\", \"info\" e \"debug\"",
	ConfFile,
	"Il file di configurazione da usare",
	LogFile,
	"Il file dove stampare il log",
	Pretty,
	"Se questa opzione é settata, i messaggi sulla console saranno mostrati in modo colorato",
	NoEnv,
	"Se questa opzione é settata, le variabili di sistema saranni ignorate",
	Verbosity,
	"La verbositá del programma, un numero da 0 a 3 inclusi",
	DoTrace,
	"Attiva la modalitá di tracing",
	CfgLocation,
	"Dove scrivere il file di configurazione, uno di \"cwd\", \"user\" o \"system\"",
	CfgForce,
	"Se presente, se c'é un file di configurazione, sará sovrascritto",
	CmdlineDelimiter,
	ConfigDelimiter,
	ConfigHeader,
	"Configuratione generata il {{ date }}",
	ConfigDelimiter,
}
